/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Options.java
 *
 * Created on 31/Mar/2011, 5:57:25
 */

package maze.gui;

import javax.swing.JOptionPane;
/**
* Classe que extende um JFrame que é responsavel pelo menu de Opcoes de jogo
* @author Tiago Mota ei09068
*/
public class Options extends javax.swing.JFrame {
	
	private static final long serialVersionUID = 1L;
	OpcaoDoJogo opc= new OpcaoDoJogo();
	private int escolha = 0;
	/**
	 * Construtor da classe Options
	 */
	public Options() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jAle = new javax.swing.JCheckBox();
		jPreD = new javax.swing.JCheckBox();
		jLabel3 = new javax.swing.JLabel();
		size = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		nrDrags = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		jCombDragMov = new javax.swing.JComboBox();
		
		
		okBt = new javax.swing.JButton();
		ExitBt = new javax.swing.JButton();

		size.setText(Integer.toString(opc.getTamanhoLabirinto()));
		nrDrags.setText(Integer.toString(opc.getNumeroDragao()));
		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setText("Game options");
		jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

		jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel2.setText("Tipo de Labirinto:");

		jAle.setText("Aleatorio");
		

		jPreD.setText("Pre-definido");
		

		jLabel3.setText("Tamanho do Labirinto: ");

		jLabel4.setText("Numero de Dragoes: ");

		jLabel5.setText("Modo de movimento do Dragao: ");

		jCombDragMov.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Parado", "Aleatorio", "Adormecer com Aleatorio" }));
		

		

		

		okBt.setText("Ok");
		okBt.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				okBtActionPerformed(evt);
			}
		});

		ExitBt.setText("Sair");
		ExitBt.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ExitBtActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(428, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nrDrags)
                            .addComponent(size, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(21, 21, 21)
                        .addComponent(jCombDragMov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jAle)
                        .addGap(29, 29, 29)
                        .addComponent(jPreD)
                        .addGap(34, 34, 34))))
            .addGroup(layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(okBt)
                .addGap(59, 59, 59)
                .addComponent(ExitBt)
                .addContainerGap(220, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPreD)
                            .addComponent(jAle)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(nrDrags, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jCombDragMov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okBt)
                    .addComponent(ExitBt))
                .addContainerGap())
        );

        pack();
    }

	/**
	 * Função que define o evento do botao ok desta janela de opcoes
	 * @param evt
	 */
	private void okBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtActionPerformed
		opc.setTipoDragao(jCombDragMov.getSelectedIndex()+1);

		String tamanho = size.getText();
		String drags = nrDrags.getText();
		
		int error = 0;
		int numeroTamanho = 0;
		if(jAle.isSelected() == false && jPreD.isSelected() == false){
			JOptionPane.showMessageDialog(null, "Tem de escolher o tipo de labirinto!");
			error = 1;
		}
		if(jAle.isSelected() == true){
			if (tamanho.equals("")){
				JOptionPane.showMessageDialog(null, "O tamanho do labirinto esta vazio!!!");
				error = 1;
			} else{
				numeroTamanho = Integer.parseInt(tamanho);
				if (numeroTamanho<10){
					JOptionPane.showMessageDialog(null, "Tamanho minimo = 10!\n Input dado = " + numeroTamanho);
					error = 1;
				}
				else if(drags.equals("") || drags.equals("0")){
					JOptionPane.showMessageDialog(null, "Tem de ter pelo menos 1 Dragao!");
					error = 1;
				}
			}
			
		}
		if(jAle.isSelected() == true){
			if(jPreD.isSelected() == true){
				JOptionPane.showMessageDialog(null, "Apenas pode escolher\num tipo de Labirinto!");
				error = 1;
			}
			else{
				escolha = 1;
			}
		}
		if(jPreD.isSelected() == true){
			if(jAle.isSelected() == true){
				JOptionPane.showMessageDialog(null, "Apenas pode escolher\num tipo de Labirinto!");
				error = 1;
			}
			else{
				escolha = 2;
			}
		}
		
		int numeroD = Integer.parseInt(drags);
		if(numeroD > 4){
			JOptionPane.showMessageDialog(null, "Escolhe no maximo 4 Dragoes!" );
			error=1;
		}
		if (error == 0){
			opc.setTipoLab(escolha);
			if(escolha == 1){
				opc.setTamanhoLabirinto(numeroTamanho);
				String nDrag = nrDrags.getText();
				this.getOpcao().setNumeroDragao(Integer.parseInt(nDrag));
			}
			this.dispose();
		}



	}
	/**
	 * Função que define o evento quando se carrega no botao exit
	 * @param evt
	 */
	private void ExitBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtActionPerformed
		this.dispose();
	}

	

	private javax.swing.JButton ExitBt;
	
	private javax.swing.JCheckBox jAle;
	private javax.swing.JComboBox jCombDragMov;
	private javax.swing.JLabel jLabel1;
	
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	
	private javax.swing.JCheckBox jPreD;
	

	private javax.swing.JTextField nrDrags;
	private javax.swing.JButton okBt;
	
	private javax.swing.JTextField size;
	

	public void setOpcao(OpcaoDoJogo opcao) {
		size.setText(Integer.toString(opcao.getTamanhoLabirinto()));
		nrDrags.setText(Integer.toString(opcao.getNumeroDragao()));
		jCombDragMov.setSelectedItem(opcao.getTipoDragao());
		
		opc = opcao;
	}
	public OpcaoDoJogo getOpcao(){
		return opc;
	}
}
